FROM python:3.12
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TZ=Europe/Moscow
RUN mkdir -p /usr/local/home_services
RUN pip3 install --upgrade pip
COPY ./ /usr/local/home_services
RUN pip3 install -r /usr/local/home_services/requirements.txt
WORKDIR /usr/local/home_services

# Start
CMD cd /usr/local/home_services && \
uvicorn main:app --host 0.0.0.0 --port 8004 --reload
